language: node_js

node_js:
  - '6'
  - '8'
  - '10'

env:
  - TARGET=ci-npm

script:
  - npm run lint
  - npm run $TARGET

deploy:
  provider: pages
  local-dir: breakage
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
