language: node_js
node_js:
  - '8'
  - '10'
script:
  - npm run lint
  - npm run ci || true
deploy:
  provider: pages
  local-dir: breakage
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
