#!/usr/bin/env node

const childProcess = require('child_process');

console.log('>>> installing modules..');

childProcess.spawnSync('npm install', {
  cwd: process.cwd(),
  shell: true,
  stdio: 'inherit'
});

const canaryVersion = process.env.CANARY_VERSION || 'latest';
const unexpectedPackage = `unexpected@${canaryVersion}`;

console.log('>>> installing ' + unexpectedPackage);

childProcess.spawnSync(`npm install ${unexpectedPackage}`, {
  cwd: process.cwd(),
  shell: true,
  stdio: 'inherit'
});
